CREATE TABLE [dbo].[StudentGuardians]
(
	GuardianId INT NOT NULL PRIMARY KEY identity,
	StudentId int foreign key references dbo.Student(StudentId),
	Title varchar(12),
	FirstName varchar(120),
	LastName varchar(120),
	Gender INT,
	Email varchar(255),
	ReleationShip int foreign key references dbo.UserRelationship (RelationshipId),
	Occupation varchar(255) NOT NULL,
	[DateOfBirth] DATETIME NOT NULL,
	PrimaryGuardian bit,
	AnnualIncome varchar(120),
	HighestQualification varchar(50),
	IsSameAsUserAddress bit,
	MobileNumber varchar(20) NOT NULL,
	OfficeNumber varchar(20),
	IsVerified bit,
	SMSEnabled bit,
	NotificationEnabled bit,
	IsDeleted bit,
	CreatedDate datetime,
	ModifiedDate datetime
)
