CREATE TABLE [dbo].[UserAccounts]
(
	UserId INT NOT NULL PRIMARY KEY identity,
	Title INT foreign key references dbo.UserTitles(UserTitleId),
	FirstName varchar(120),
	LastName varchar(120),
	UserName varchar(120) NULL,
	Email varchar(255) NULL,
	UserRole int foreign key references dbo.ApplicationRoles (RoleId),
	Gender varchar(10) NOT NULL,
	DateOfBirth datetime,
	PlaceOfBirth varchar(120),
	BloodGroup varchar(10),
	Religion varchar(50),
	Nationality varchar(50),
	Community int foreign key references dbo.CommunityMaster (CommunityId),
	CommunityInDetails varchar(255),
	MobileNumber varchar(15),
	UserStatus int foreign key references dbo.UserStatus (StatusId),
	MotherLanguage int foreign key references dbo.MotherLanguages (LanguageId),
	IsVerified bit,
	IsLocked bit,
	SMSEnabled bit,
	EmailEnabled bit,
	NotificationEnabled bit,
	UserLastLogin datetime,
	LoginEnabled bit,
	IsDeleted bit,
	CreatedDate datetime,	
	ModifiedDate datetime	
)
